### ISSUE TITLE
Crash in macOS because of xrdb dependency

### ISSUE THREAD

**Issue by grubersjoe** [channel-42/hue-tui#3]
Hey, thanks for sharing this, it's a very cool and useful :). Unfortunately, I noticed that `huetui` crashes in macOS because `xrdb` is not available here: 

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/huetui", line 8, in <module>
    r = Root(5, 4, "Hue TUI", b, c)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/huetui/frontend/root.py", line 13, in __init__
    MainWindow(root, bridge, config)
  File "/opt/homebrew/lib/python3.11/site-packages/huetui/frontend/main_window.py", line 179, in __init__
    self.light_menu = self.master.add_light_menu("Lights", 1, 0, 2, 2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/huetui/frontend/main_window.py", line 50, in add_light_menu
    new_light_menu = LightMenu(
                     ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/huetui/frontend/lights_menu.py", line 45, in __init__
    colors, err = subprocess.Popen(
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xrdb'
```

After installing it via [Homebrew](https://formulae.brew.sh/formula/xrdb) `huetui` starts and works, though 👍. However, this is more a workaround, `xrdb -query` will still not return results on macOS. So I would suggest to check if `xrdb` is available at runtime (or maybe alternatively check the OS) before calling it. If you like I can also do a PR.

**Comment by channel-42** [comment]
Hey 👋🏻
thanks for the feedback. I'm going to have a look at this on the coming weekend 😊
If you have time to implement a fix before that I'll gladly merge it 👍🏻

**Comment by channel-42** [comment]
Hey, sorry for only getting back to you now.
Can you check if 3950e74015e0612ae2f40ca18dcc7b116da6416c fixes the issue for you? 😊

**Comment by grubersjoe** [comment]
Hey. Thanks for fixing this so quickly! I can confirm that it works nicely on macOS now 👍. Even when `xrdb` is not installed.
