### ISSUE TITLE
[bug] list index out of range

### ISSUE THREAD

**Issue by TheSandBoxMKG** [channel-42/hue-tui#4]
Initial setup is OK but this happens when trying to run the software after the initial setup:
```
Traceback (most recent call last):
  File "/usr/bin/huetui", line 8, in <module>
    r = Root(5, 4, "Hue TUI", b, c)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/huetui/frontend/root.py", line 13, in __init__
    MainWindow(root, bridge, config)
  File "/usr/lib/python3.11/site-packages/huetui/frontend/main_window.py", line 179, in __init__
    self.light_menu = self.master.add_light_menu("Lights", 1, 0, 2, 2)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/huetui/frontend/main_window.py", line 50, in add_light_menu
    new_light_menu = LightMenu(
                     ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/huetui/frontend/lights_menu.py", line 64, in __init__
    xrdb_colors = get_xrdb_colors()
                  ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/huetui/frontend/utils.py", line 29, in get_xrdb_colors
    "black": colors[0],
             ~~~~~~^^^
IndexError: list index out of range
```

**Comment by channel-42** [comment]
Hey 👋🏼
Can you provide me with the output of `xrdb -query` on your system? 
I think this bug may occur, when xrdb is installed, but no colors are set in `.Xresources`.

**Comment by jasalt** [comment]
@channel-42 I had similar issue on Debian 12 (Mx Linux KDE), 3.11.2, installed hue-tui from pipx. Unfamiliar with .Xresources but here's output for the given command:

```
$ xrdb -query                                                                                                                                            1 ↵
*customization: -color
Xcursor.size:   24
Xcursor.theme:  breeze_cursors
Xft.antialias:  1
Xft.hinting:    1
Xft.hintstyle:  hintslight
Xft.rgba:       rgb
```

Inspecting what is happening with the in `utils.py` code, parser clearly fails and indexing the empty array causes exception:
```
colors, err = subprocess.Popen(
                ["xrdb", "-query"], stdout=subprocess.PIPE
            ).communicate()

# colors => b'*customization:\t-color\nXcursor.size:\t24\nXcursor.theme:\tbreeze_cursors\nXft.antialias:\t1\nXft.hinting:\t1\nXft.hintstyle:\thintslight\nXft.rgba:\trgb\n'

colors = colors.decode().split("\n")

# colors => []
```

Worked by adding `return None` before returning the dict where `colors[0]` causes the failure.

**Comment by channel-42** [comment]
@jasalt thanks for the info! Should be fixed with the commit linked above 😊
I'll release a new version shortly.
